### ISSUE TITLE
Unable to load redis_cache

### ISSUE THREAD

**Issue by clsdaniel** [jazzband/django-redis#20]
I tried using django-redis but it trows this error in production only, probably the combination of software versions is causing this:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/coclea_virt_env/lib/python2.6/site-packages/Django-1.4.2-py2.6.egg/django/core/management/**init**.py", line 443, in execute_from_command_line
    utility.execute()
  File "/srv/coclea_virt_env/lib/python2.6/site-packages/Django-1.4.2-py2.6.egg/django/core/management/**init**.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/coclea_virt_env/lib/python2.6/site-packages/Django-1.4.2-py2.6.egg/django/core/management/base.py", line 196, in run_from_argv
    self.execute(_args, *_options.**dict**)
  File "/srv/coclea_virt_env/lib/python2.6/site-packages/Django-1.4.2-py2.6.egg/django/core/management/base.py", line 217, in execute
    translation.activate('en-us')
  File "/srv/coclea_virt_env/lib/python2.6/site-packages/Django-1.4.2-py2.6.egg/django/utils/translation/**init**.py", line 105, in activate
    return _trans.activate(language)
  File "/srv/coclea_virt_env/lib/python2.6/site-packages/Django-1.4.2-py2.6.egg/django/utils/translation/trans_real.py", line 194, in activate
    _active.value = translation(language)
  File "/srv/coclea_virt_env/lib/python2.6/site-packages/Django-1.4.2-py2.6.egg/django/utils/translation/trans_real.py", line 183, in translation
    default_translation = _fetch(settings.LANGUAGE_CODE)
  File "/srv/coclea_virt_env/lib/python2.6/site-packages/Django-1.4.2-py2.6.egg/django/utils/translation/trans_real.py", line 160, in _fetch
    app = import_module(appname)
  File "/srv/coclea_virt_env/lib/python2.6/site-packages/Django-1.4.2-py2.6.egg/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/srv/coclea_virt_env/lib/python2.6/site-packages/django_redis-3.1.2-py2.6.egg/redis_cache/**init**.py", line 3, in <module>
    from django.core.cache import get_cache
  File "/srv/coclea_virt_env/lib/python2.6/site-packages/Django-1.4.2-py2.6.egg/django/core/cache/**init**.py", line 187, in <module>
    cache = get_cache(DEFAULT_CACHE_ALIAS)
  File "/srv/coclea_virt_env/lib/python2.6/site-packages/Django-1.4.2-py2.6.egg/django/core/cache/**init**.py", line 178, in get_cache
    "Could not find backend '%s': %s" % (backend, e))
django.core.cache.backends.base.InvalidCacheBackendError: Could not find backend 'redis_cache.cache.RedisCache': 'tuple' object has no attribute 'major'

Software Debian 6.0 (Squeeze):
- Python 2.6.6
- redis-py 2.7.1
- django_redis 3.1.2
- django 1.4.2
- redis 2.4.11

**Comment by jdelafon** [comment]
In case it helps anybody, I had this issue when calling "python manage.py", even when it looks into looks into python3.5/site-packages and "python" opens Python 3.5.1. Instead, "python3 manage.py" works fine (still 3.5.1). Weird.

**Comment by grv07** [comment]
pip install django-redis, solve my issue
