### ISSUE TITLE
Serialization with msgpack 0.5.4

### ISSUE THREAD

**Issue by peterbe** [jazzband/django-redis#310]
I have a [project](https://github.com/mozilla-services/tecken) that uses django-redis ([version 4.8.0](https://github.com/mozilla-services/tecken/blob/f3edf42a62420ef6a701438933d4a4ddb1678507/requirements.txt#L83)).

When upgrading msgpack things break. See [this PR's](https://github.com/mozilla-services/tecken/pull/724) [CircleCI failure](https://circleci.com/gh/mozilla-services/tecken/3060?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link). 

I can reproduce it every time locally. The traceback looks like this:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django_redis/client/default.py", line 313, in decode
    value = int(value)
ValueError: invalid literal for int() with base 10: b'\x92\xce\x00&y\x1a\xce\x00\xb2\xe3\xf7'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/tests/test_symbolicate.py", line 478, in test_symbolicate_v4_json_lru_causing_mischief
    }, debug=True)
  File "/app/tests/conftest.py", line 43, in inner
    return client.post(url, data, **extra)
  File "/usr/local/lib/python3.6/site-packages/django/test/client.py", line 525, in post
    response = super().post(path, data=data, content_type=content_type, secure=secure, **extra)
  File "/usr/local/lib/python3.6/site-packages/django/test/client.py", line 341, in post
    secure=secure, **extra)
  File "/usr/local/lib/python3.6/site-packages/django/test/client.py", line 404, in generic
    return self.request(**r)
  File "/usr/local/lib/python3.6/site-packages/django/test/client.py", line 467, in request
    response = self.handler(environ)
  File "/usr/local/lib/python3.6/site-packages/django/test/client.py", line 138, in __call__
    response = self.get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 81, in get_response
    response = self._middleware_chain(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 37, in inner
    response = response_for_exception(request, exc)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 87, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/utils/deprecation.py", line 95, in __call__
    response = self.get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 37, in inner
    response = response_for_exception(request, exc)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 87, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/utils/deprecation.py", line 95, in __call__
    response = self.get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 37, in inner
    response = response_for_exception(request, exc)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 87, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/utils/deprecation.py", line 95, in __call__
    response = self.get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 37, in inner
    response = response_for_exception(request, exc)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 87, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/utils/deprecation.py", line 95, in __call__
    response = self.get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 37, in inner
    response = response_for_exception(request, exc)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 87, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/utils/deprecation.py", line 95, in __call__
    response = self.get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 37, in inner
    response = response_for_exception(request, exc)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 87, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/app/tecken/tokens/middleware.py", line 34, in __call__
    response = self.get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 37, in inner
    response = response_for_exception(request, exc)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 87, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/whitenoise/middleware.py", line 25, in __call__
    response = self.get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 37, in inner
    response = response_for_exception(request, exc)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 87, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/tecken/base/decorators.py", line 165, in inner
    response = func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/tecken/base/decorators.py", line 100, in wrapper
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/markus/main.py", line 357, in _timer_decorator
    return fun(*args, **kwargs)
  File "/app/tecken/symbolicate/views.py", line 746, in inner
    return view_function(request, json_body)
  File "/app/tecken/symbolicate/views.py", line 770, in symbolicate_v4_json
    result = symbolicator.symbolicate(stacks, memory_map)
  File "/app/tecken/symbolicate/views.py", line 146, in symbolicate
    informations = self.get_symbol_offsets(needed_modules_lookups)
  File "/usr/local/lib/python3.6/site-packages/markus/main.py", line 357, in _timer_decorator
    return fun(*args, **kwargs)
  File "/app/tecken/symbolicate/views.py", line 449, in get_symbol_offsets
    all_keys = store.get_many(cache_keys_keys)
  File "/usr/local/lib/python3.6/site-packages/django_redis/cache.py", line 33, in _decorator
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django_redis/cache.py", line 109, in get_many
    return self.client.get_many(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django_redis/client/default.py", line 359, in get_many
    recovered_data[map_keys[key]] = self.decode(value)
  File "/usr/local/lib/python3.6/site-packages/django_redis/client/default.py", line 320, in decode
    value = self._serializer.loads(value)
  File "/usr/local/lib/python3.6/site-packages/django_redis/serializers/msgpack.py", line 15, in loads
    return msgpack.loads(value, encoding="utf-8")
  File "msgpack/_unpacker.pyx", line 189, in msgpack._unpacker.unpackb
PendingDeprecationWarning: encoding is deprecated, Use raw=False instead.
```

The only code in there that is mine is:
```python
all_keys = store.get_many(cache_keys_keys)
```
...where
```python
from django.core.cache import caches
store = caches['store']
cache_keys_keys = ['symbol:a063e:xul.pdb/44E4EC8C2F41492B9369D6B9A059577C2:keys', 'symbol:a063e:wntdll.pdb/D74F79EB1F8D4A45ABCD2F476CCABACC2:keys']
```

**Comment by peterbe** [comment]
One thing I noticed was that if I edit `site-packages/django_redis/serializers/msgpack.py` and remove the `encoding="utf-8"` from `msgpack.loads` then things work again. I.e. this diff:

```diff
class MSGPackSerializer(BaseSerializer):
    def dumps(self, value):
        return msgpack.dumps(value)

    def loads(self, value):
-       return msgpack.loads(value, encoding="utf-8")
+       return msgpack.loads(value)
```

**Comment by peterbe** [comment]
Ah! Now I understand what I can't reproduce this with a simple Django shell. My pytest is set up to turn any warnings into errors. 
```
# In pytest.ini
[pytest]
# other stuff

# Transform all warnings into errors
filterwarnings = error
```

To demonstrate this:
```
>>> import warnings
>>> warnings.filterwarnings('error')
>>> from django.core.cache import caches
>>> store = caches['store']
>>> store.set('foo', [123])
True
>>> store.get_many(['foo'])
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django_redis/client/default.py", line 313, in decode
    value = int(value)
ValueError: invalid literal for int() with base 10: b'\x91{'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/django_redis/cache.py", line 33, in _decorator
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django_redis/cache.py", line 109, in get_many
    return self.client.get_many(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django_redis/client/default.py", line 359, in get_many
    recovered_data[map_keys[key]] = self.decode(value)
  File "/usr/local/lib/python3.6/site-packages/django_redis/client/default.py", line 320, in decode
    value = self._serializer.loads(value)
  File "/usr/local/lib/python3.6/site-packages/django_redis/serializers/msgpack.py", line 15, in loads
    return msgpack.loads(value, encoding="utf-8")
  File "msgpack/_unpacker.pyx", line 189, in msgpack._unpacker.unpackb
PendingDeprecationWarning: encoding is deprecated, Use raw=False instead.
```

For what it's worth, that `store` configuration (from `caches['store']`) looks like this:
```
'store': {
    'BACKEND': 'django_redis.cache.RedisCache',
    'LOCATION': self.REDIS_STORE_URL,
    'OPTIONS': {
        'COMPRESSOR': 'django_redis.compressors.zlib.ZlibCompressor',  # noqa
        'SERIALIZER': 'django_redis.serializers.msgpack.MSGPackSerializer',  # noqa
    },
},
```

**Comment by niwinz** [comment]
Hmm, seems like encoding is deprecated in mspack, and your warning config is converting this warning on error.

**Comment by niwinz** [comment]
But changing it from `encoding="utf-8"` to `raw=False` makes django-redis automatically incompatible with msgpack `0.5.1` (and probably others). I'm not clearly convinced of this change. Just removing the `encoding` is not a solution because serialized strings are returned as bytes and this is also incosistent.

**Comment by peterbe** [comment]
Tricky. I actually don't have a solution. 

There's some intermediate solutions we might apply such as forcing a dependency on `msgpack < 0.5.4` (or whatever the actual details indicate). 

On my end, I don't actually have to upgrade `msgpack` since it's only ever used for `django-redis`. Or, I could change my pytest config so allow deprecation warnings (not attractive).

**Comment by peterbe** [comment]
Here's what I had to do to my project: https://github.com/mozilla-services/tecken/blob/e49cc259aa968a7d988800d09fc8460b3e30a6e6/tecken/cache_extra.py#L49-L62

Basically, I really wanted to upgrade to msgpack 0.6.0 and if I do that, and at the same time turn deprecation warnings into errors, it would not work. 

I can "afford" to make this change because I know I won't have to worry about breaking compatibility for older versions of msgpack. 

Leaving this here might help others. 

The more sustainable change would be for django_redis to have something like `msgpack > 0.5.4` in some conditional trick in `setup.py`. (haven't looked at the details of that possibility).

**Comment by sevdog** [comment]
This may be adjusted by using an option to specify `msgpack` compatibility, like `PickleSerializer` does.

**Comment by skoot** [comment]
The deprecation warning is now a full blown exception, this issue needs to be adressed.

**Comment by jdufresne** [comment]
Since 1bbfde21572eba80e306d63f77c71fe06b73810d, msgpack `>=0.6.0` is required.

The msgpack serializer no longer uses the deprecated API.

If you continue to have issues after updating, please report the details here.

**Comment by fermayo** [comment]
> The msgpack serializer no longer uses the deprecated API.

The fix that stops using the deprecated msgpack API is actually in 7aad69ed11c84c4c1ea1f992b01b652ba173a2b1, which is not yet released. So the latest version of `django-redis` (4.11.0) does not work with `msgpack 1.0.0`.
