### ISSUE TITLE
_pickle.PicklingError: Can't pickle <class 'uuid.UUID'>: it's not the same object as uuid.UUID

### ISSUE THREAD

**Issue by artemistomaras** [jazzband/django-redis#319]
I have a model that has a field that looks like this:
`uuid = models.UUIDField(unique=True, default=uuid.uuid4, editable=False)`

I use [django-cachalot ](https://github.com/BertrandBordage/django-cachalot) along with django-redis in order to cache my querysets. I have deployed my application with apache2.

After a few days, I get the following error in my deployed environment:

```
 [26/Mar/2018 07:12:57] - [django.request:124] - [ERROR] Internal Server Error: /en/api/v1/water/installations/participating
 Traceback (most recent call last):
   File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 39, in inner
     response = get_response(request)
   File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
     response = self._get_response(request)
   File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 187, in _get_response
     response = self.process_exception_by_middleware(e, request)
   File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 185, in _get_response
     response = wrapped_callback(request, *callback_args, **callback_kwargs)
   File "/usr/local/lib/python3.5/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
     return view_func(*args, **kwargs)
   File "/usr/local/lib/python3.5/dist-packages/django/views/generic/base.py", line 68, in view
     return self.dispatch(request, *args, **kwargs)
   File "/usr/local/lib/python3.5/dist-packages/rest_framework/views.py", line 477, in dispatch
     response = self.handle_exception(exc)
   File "/usr/local/lib/python3.5/dist-packages/rest_framework/views.py", line 437, in handle_exception
     self.raise_uncaught_exception(exc)
   File "/usr/local/lib/python3.5/dist-packages/rest_framework/views.py", line 474, in dispatch
     response = handler(request, *args, **kwargs)
   File "/usr/local/lib/python3.5/dist-packages/rest_framework/generics.py", line 200, in get
     return self.list(request, *args, **kwargs)
   File "/usr/local/lib/python3.5/dist-packages/rest_framework/mixins.py", line 48, in list
     return Response(serializer.data)
   File "/usr/local/lib/python3.5/dist-packages/rest_framework/serializers.py", line 725, in data
     ret = super(ListSerializer, self).data
   File "/usr/local/lib/python3.5/dist-packages/rest_framework/serializers.py", line 262, in data
     self._data = self.to_representation(self.instance)
   File "/usr/local/lib/python3.5/dist-packages/rest_framework/serializers.py", line 643, in to_representation
     self.child.to_representation(item) for item in iterable
   File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 256, in __iter__
     self._fetch_all()
   File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 1087, in _fetch_all
     self._result_cache = list(self.iterator())
   File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 54, in __iter__
     results = compiler.execute_sql()
   File "/usr/local/lib/python3.5/dist-packages/cachalot/monkey_patch.py", line 32, in inner
     out = original(compiler, *args, **kwargs)
   File "/usr/local/lib/python3.5/dist-packages/cachalot/monkey_patch.py", line 84, in inner
     cache_key, table_cache_keys)
   File "/usr/local/lib/python3.5/dist-packages/cachalot/monkey_patch.py", line 59, in _get_result_or_execute_query
     cache.set(cache_key, (time(), result), cachalot_settings.CACHALOT_TIMEOUT)
   File "/usr/local/lib/python3.5/dist-packages/django_redis/cache.py", line 33, in _decorator
     return method(self, *args, **kwargs)
   File "/usr/local/lib/python3.5/dist-packages/django_redis/cache.py", line 68, in set
     return self.client.set(*args, **kwargs)
   File "/usr/local/lib/python3.5/dist-packages/django_redis/client/default.py", line 109, in set
     nvalue = self.encode(value)
   File "/usr/local/lib/python3.5/dist-packages/django_redis/client/default.py", line 329, in encode
     value = self._serializer.dumps(value)
   File "/usr/local/lib/python3.5/dist-packages/django_redis/serializers/pickle.py", line 33, in dumps
     return pickle.dumps(value, self._pickle_version)
 _pickle.PicklingError: Can't pickle <class 'uuid.UUID'>: it's not the same object as uuid.UUID
```

If a restart my apache server, _the error goes away_. I have not managed to reproduce the same error locally.

The packages I use are:
```
Django==1.10.5
django-cachalot==1.5.0
django-redis==4.8.0
djangorestframework==3.5.3
```

and my relevant redis settings are:
```
    'orm_cache': {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://{}:{}/{}".format(REDIS_IP, REDIS_PORT, REDIS_ORM_CACHE_DATABASE),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "PASSWORD": REDIS_PASSWORD
        },
        "TIMEOUT": 2 * ORM_CACHE_TIMEOUT
    }
```

Any ideas as to why I get this nasty error?

**Comment by niwinz** [comment]
No idea why this happens. Is not directly related to django redis. Seems like a corner case of pickle.

**Comment by jdufresne** [comment]
Closing as this looks unrelated to django-redis itself. If you can demonstrate that django-redis is at fault, please provide the details.
