### ISSUE TITLE
django.core.cache.backends.base.InvalidCacheBackendError: Could not find backend 'django_redis.cache.RedisCache': cannot import name 'get_cache'

### ISSUE THREAD

**Issue by golangav** [jazzband/django-redis#466]
django==2.2
django-redis==3.8.4

Performing system checks...

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/cache/__init__.py", line 50, in _create_cache
    backend_cls = import_string(backend)
  File "/usr/local/lib/python3.6/site-packages/django/utils/module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.6/site-packages/django_redis/__init__.py", line 3, in <module>
    from django.core.cache import get_cache
ImportError: cannot import name 'get_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 16, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 60, in execute
    super().execute(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 95, in handle
    self.run(**options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 102, in run
    autoreload.run_with_reloader(self.inner_run, **options)
  File "/usr/local/lib/python3.6/site-packages/django/utils/autoreload.py", line 579, in run_with_reloader
    start_django(reloader, main_func, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/utils/autoreload.py", line 564, in start_django
    reloader.run(django_main_thread)
  File "/usr/local/lib/python3.6/site-packages/django/utils/autoreload.py", line 272, in run
    get_resolver().urlconf_module
  File "/usr/local/lib/python3.6/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.6/site-packages/django/urls/resolvers.py", line 564, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/shaowei/anchnet/ecloud/smartant_backend_ecloud/apps/smartant_backend/urls.py", line 24, in <module>
    namespace='api-accounts-v2')),
  File "/usr/local/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/shaowei/anchnet/ecloud/smartant_backend_ecloud/apps/accounts/urls/api_v2_urls.py", line 3, in <module>
    from accounts.api import accounts_v2
  File "/Users/shaowei/anchnet/ecloud/smartant_backend_ecloud/apps/accounts/api/accounts_v2.py", line 1, in <module>
    from rest_framework.views import APIView
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 19, in <module>
    from rest_framework.schemas import DefaultSchema
  File "/usr/local/lib/python3.6/site-packages/rest_framework/schemas/__init__.py", line 32, in <module>
    authentication_classes=api_settings.DEFAULT_AUTHENTICATION_CLASSES,
  File "/usr/local/lib/python3.6/site-packages/rest_framework/settings.py", line 220, in __getattr__
    val = self.user_settings[attr]
  File "/usr/local/lib/python3.6/site-packages/rest_framework/settings.py", line 211, in user_settings
    self._user_settings = getattr(settings, 'REST_FRAMEWORK', {})
  File "/Users/shaowei/anchnet/ecloud/smartant_backend_ecloud/apps/common/signals_handler.py", line 30, in monkey_patch_getattr
    cached = cache.get(key)
  File "/usr/local/lib/python3.6/site-packages/django/core/cache/__init__.py", line 98, in __getattr__
    return getattr(caches[DEFAULT_CACHE_ALIAS], name)
  File "/usr/local/lib/python3.6/site-packages/django/core/cache/__init__.py", line 79, in __getitem__
    cache = _create_cache(alias)
  File "/usr/local/lib/python3.6/site-packages/django/core/cache/__init__.py", line 53, in _create_cache
    "Could not find backend '%s': %s" % (backend, e))
django.core.cache.backends.base.InvalidCacheBackendError: Could not find backend 'django_redis.cache.RedisCache': cannot import name 'get_cache

**Comment by jdufresne** [comment]
Looks like an issue with your installation or your virtualenv. Cannot reproduce.

**Comment by jdufresne** [comment]
Can you link to a minimal project that demonstrates the issue with djang-redis?
