### ISSUE TITLE
ValueError: unsupported pickle protocol: 5

### ISSUE THREAD

**Issue by chenguanyou** [jazzband/django-redis#485]
/
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django_redis/client/default.py", line 311, in decode
    value = int(value)
ValueError: invalid literal for int() with base 10: b'\x80\x05\x95\x03\x17\x00\x00\x00\x00\x00\x00]\x94(GA\xd7\xf4\x07^\x80\x0e\x80GA\xd7\xf3\xd5-\x8f,fGA\xd7\xf3\xd5+\xf0P\x1eGA\xd7\xf3\xd5+\x17\x1cvGA\xd7\xf3\xd5)\x8c\xcb[GA\xd7\xf3\xd5)\x7f6\xa4GA\x

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rest_framework/viewsets.py", line 116, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    self.initial(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rest_framework/views.py", line 402, in initial
    self.check_throttles(request)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rest_framework/views.py", line 356, in check_throttles
    if not throttle.allow_request(request, self):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rest_framework/throttling.py", line 125, in allow_request
    self.history = self.cache.get(self.key, [])
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django_redis/cache.py", line 32, in _decorator
    return method(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django_redis/cache.py", line 81, in get
    client=client)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django_redis/client/default.py", line 210, in get
    return self.decode(value)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django_redis/client/default.py", line 318, in decode
    value = self._serializer.loads(value)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django_redis/serializers/pickle.py", line 35, in loads
    return pickle.loads(value)
ValueError: unsupported pickle protocol: 5

**Comment by irfanpule** [comment]
Hai @chenguanyou , how do you solve this issue? I get same issue after after upgrade OS, but I still create env with same python version.

**Comment by irfanpule** [comment]
I got it. Enter into redis-cli and `FLUSSALL`
