### ISSUE TITLE
Using ZstdCompressor fails Pytest to Launch

### ISSUE THREAD

**Issue by erayerdin** [jazzband/django-redis#561]
**Describe the bug**
Setting up `CACHES["default"]["OPTIONS"]["COMPRESSOR"]` to `"django_redis.compressors.zstd.ZStdCompressor"` fails to launch `pytest`.

**To Reproduce**

**Step 1**: Set up a Django project. (mine uses [this](https://github.com/erayerdin/sos-django-template) template)

**Step 2**: Set the caching options as below:

```python
# Caches
CACHES = {}

# Redis Caches
CACHES["default"] = {
    "BACKEND": "django_redis.cache.RedisCache",
    "LOCATION": env("REDIS_CACHE_LOCATION"),  # set it on .env
    "OPTIONS": {
        "CLIENT_CLASS": "django_redis.client.DefaultClient",
        "PASSWORD": env("REDIS_PASSWORD"),  # set it on .env
        "COMPRESSOR": "django_redis.compressors.zstd.ZStdCompressor",
    },
}
```

**Step 3**: Install `pyzstd` with poetry.

**Step 4**: Fire up `pytest` and get the error.

**Expected behavior**
For pytest to run without any error.

**Stack trace**

Here it is:

```plain
Traceback (most recent call last):
  File "/home/erayerdin/.cache/pypoetry/virtualenvs/myproject-DwOC5Dji-py3.9/lib/python3.9/site-packages/pytest_django/plugin.py", line 178, in _handle_import_error
    yield
  File "/home/erayerdin/.cache/pypoetry/virtualenvs/myproject-DwOC5Dji-py3.9/lib/python3.9/site-packages/pytest_django/plugin.py", line 347, in pytest_load_initial_conftests
    dj_settings.DATABASES
  File "/home/erayerdin/.cache/pypoetry/virtualenvs/myproject-DwOC5Dji-py3.9/lib/python3.9/site-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/home/erayerdin/.cache/pypoetry/virtualenvs/myproject-DwOC5Dji-py3.9/lib/python3.9/site-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/erayerdin/.cache/pypoetry/virtualenvs/myproject-DwOC5Dji-py3.9/lib/python3.9/site-packages/django/conf/__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/erayerdin/Documents/Projects/Programming/myproject/backend/project/settings/development.py", line 31, in <module>
    cache.clear()
  File "/home/erayerdin/.cache/pypoetry/virtualenvs/myproject-DwOC5Dji-py3.9/lib/python3.9/site-packages/django_redis/cache.py", line 31, in _decorator
    return method(self, *args, **kwargs)
  File "/home/erayerdin/.cache/pypoetry/virtualenvs/myproject-DwOC5Dji-py3.9/lib/python3.9/site-packages/django_redis/cache.py", line 117, in clear
    return self.client.clear()
  File "/home/erayerdin/.cache/pypoetry/virtualenvs/myproject-DwOC5Dji-py3.9/lib/python3.9/site-packages/django_redis/cache.py", line 75, in client
    self._client = self._client_cls(self._server, self._params, self)
  File "/home/erayerdin/.cache/pypoetry/virtualenvs/myproject-DwOC5Dji-py3.9/lib/python3.9/site-packages/django_redis/client/default.py", line 57, in __init__
    compressor_cls = import_string(compressor_path)
  File "/home/erayerdin/.cache/pypoetry/virtualenvs/myproject-DwOC5Dji-py3.9/lib/python3.9/site-packages/django/utils/module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'django_redis.compressors.zstd'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/erayerdin/.cache/pypoetry/virtualenvs/myproject-DwOC5Dji-py3.9/bin/pytest", line 8, in <module>
    sys.exit(console_main())
  File "/home/erayerdin/.cache/pypoetry/virtualenvs/myproject-DwOC5Dji-py3.9/lib/python3.9/site-packages/_pytest/config/__init__.py", line 185, in console_main
    code = main()
  File "/home/erayerdin/.cache/pypoetry/virtualenvs/myproject-DwOC5Dji-py3.9/lib/python3.9/site-packages/_pytest/config/__init__.py", line 143, in main
    config = _prepareconfig(args, plugins)
  File "/home/erayerdin/.cache/pypoetry/virtualenvs/myproject-DwOC5Dji-py3.9/lib/python3.9/site-packages/_pytest/config/__init__.py", line 318, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "/home/erayerdin/.cache/pypoetry/virtualenvs/myproject-DwOC5Dji-py3.9/lib/python3.9/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/home/erayerdin/.cache/pypoetry/virtualenvs/myproject-DwOC5Dji-py3.9/lib/python3.9/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/home/erayerdin/.cache/pypoetry/virtualenvs/myproject-DwOC5Dji-py3.9/lib/python3.9/site-packages/pluggy/_callers.py", line 55, in _multicall
    gen.send(outcome)
  File "/home/erayerdin/.cache/pypoetry/virtualenvs/myproject-DwOC5Dji-py3.9/lib/python3.9/site-packages/_pytest/helpconfig.py", line 100, in pytest_cmdline_parse
    config: Config = outcome.get_result()
  File "/home/erayerdin/.cache/pypoetry/virtualenvs/myproject-DwOC5Dji-py3.9/lib/python3.9/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/erayerdin/.cache/pypoetry/virtualenvs/myproject-DwOC5Dji-py3.9/lib/python3.9/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/home/erayerdin/.cache/pypoetry/virtualenvs/myproject-DwOC5Dji-py3.9/lib/python3.9/site-packages/_pytest/config/__init__.py", line 1003, in pytest_cmdline_parse
    self.parse(args)
  File "/home/erayerdin/.cache/pypoetry/virtualenvs/myproject-DwOC5Dji-py3.9/lib/python3.9/site-packages/_pytest/config/__init__.py", line 1283, in parse
    self._preparse(args, addopts=addopts)
  File "/home/erayerdin/.cache/pypoetry/virtualenvs/myproject-DwOC5Dji-py3.9/lib/python3.9/site-packages/_pytest/config/__init__.py", line 1191, in _preparse
    self.hook.pytest_load_initial_conftests(
  File "/home/erayerdin/.cache/pypoetry/virtualenvs/myproject-DwOC5Dji-py3.9/lib/python3.9/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/home/erayerdin/.cache/pypoetry/virtualenvs/myproject-DwOC5Dji-py3.9/lib/python3.9/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/home/erayerdin/.cache/pypoetry/virtualenvs/myproject-DwOC5Dji-py3.9/lib/python3.9/site-packages/pluggy/_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "/home/erayerdin/.cache/pypoetry/virtualenvs/myproject-DwOC5Dji-py3.9/lib/python3.9/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/erayerdin/.cache/pypoetry/virtualenvs/myproject-DwOC5Dji-py3.9/lib/python3.9/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/home/erayerdin/.cache/pypoetry/virtualenvs/myproject-DwOC5Dji-py3.9/lib/python3.9/site-packages/pytest_django/plugin.py", line 347, in pytest_load_initial_conftests
    dj_settings.DATABASES
  File "/usr/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/erayerdin/.cache/pypoetry/virtualenvs/myproject-DwOC5Dji-py3.9/lib/python3.9/site-packages/pytest_django/plugin.py", line 182, in _handle_import_error
    raise ImportError(msg)
ImportError: No module named 'django_redis.compressors.zstd'

pytest-django found a Django project in /home/erayerdin/Documents/Projects/Programming/myproject/backend (it contains manage.py) and added it to the Python path.
If this is wrong, add "django_find_project = false" to pytest.ini and explicitly manage your Python path.
```

**Environment**
 - Python version: 3.9.5
 - Django Redis Version: ^5.0.0
 - Django Version: ^2.2
 - Redis Version: 6.0.11
 - redis-py Version: 3.5.3

**Additional context**
 - The error is not reproducible with `lzma`. pytest runs with it.
 - Importing `pyzstd` in the beginning of settings file (as `README` puts it) does not work either.

**Comment by terencehonles** [comment]
@WisdomPill released 5.1 with #562 / #573 so this functionality should now be included. @WisdomPill any thoughts on ^^^ or do we want to just set a mor regular release cadence?

**Comment by WisdomPill** [comment]
I don't think we are the state to start making regular releases, I suggest making them as they come, we can start with release candidates, of course, for just added features that are not yet worth the full release or are not yet production ready as for your past contribution for sentinel.

**Comment by terencehonles** [comment]
@WisdomPill and what do you think about the branching strategy? or should we not bother with that?

**Comment by WisdomPill** [comment]
@terencehonles well, as a matter of fact we should also change the main branch name to `"main"` as per GitHub guidelines and so on.

I am not against creating different branches as @erayerdin pointed out, 
but let's look at the situation of things, this project does not receive tens of commits each day, 
not even a commit a day, so the master is not really something too unstable that changes too much very often.

So my question is, is it worth it to add complexity?

**Comment by WisdomPill** [comment]
for `zsdt` which raised the issue, it is more about us not putting `zstd` in the requirements than having different branches.

For me `master` or `main` branch should always be deployable, otherwise another branch for accepting PRs (for some long migration or something) should be created.

**Comment by terencehonles** [comment]
@WisdomPill I'm fine either way, and my default stance is we can keep things as they are, so it sounds like you're suggesting the same. I'm fine w/ changing the default branch, but I don't think we _need_ to (I assume the GitHub guidelines are probably a suggestion instead of a guideline?).

**Comment by WisdomPill** [comment]
@terencehonles it was just an example regarding the branches, it's not my main priority 😄
