### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by korsar182** [jazzband/django-redis#588]
>>> from django.core.cache import cache
>>> cache.set('a','b')
True
>>> cache.get('a')
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/vagrant/.local/share/virtualenvs/white-labeling-z-SFsspa/lib/python3.9/site-packages/django_redis/cache.py", line 91, in get
    value = self._get(key, default, version, client)
  File "/home/vagrant/.local/share/virtualenvs/white-labeling-z-SFsspa/lib/python3.9/site-packages/django_redis/cache.py", line 31, in _decorator
    return method(self, *args, **kwargs)
  File "/home/vagrant/.local/share/virtualenvs/white-labeling-z-SFsspa/lib/python3.9/site-packages/django_redis/cache.py", line 98, in _get
    return self.client.get(key, default=default, version=version, client=client)
  File "/home/vagrant/.local/share/virtualenvs/white-labeling-z-SFsspa/lib/python3.9/site-packages/django_redis/client/default.py", line 258, in get
    value = client.get(key)
  File "/home/vagrant/.local/share/virtualenvs/white-labeling-z-SFsspa/lib/python3.9/site-packages/redis/commands/core.py", line 1233, in get
    return self.execute_command("GET", name)
  File "/home/vagrant/.local/share/virtualenvs/white-labeling-z-SFsspa/lib/python3.9/site-packages/redis/client.py", line 1176, in execute_command
    return conn.retry.call_with_retry(
  File "/home/vagrant/.local/share/virtualenvs/white-labeling-z-SFsspa/lib/python3.9/site-packages/redis/retry.py", line 41, in call_with_retry
    return do()
  File "/home/vagrant/.local/share/virtualenvs/white-labeling-z-SFsspa/lib/python3.9/site-packages/redis/client.py", line 1177, in <lambda>
    lambda: self._send_command_parse_response(
  File "/home/vagrant/.local/share/virtualenvs/white-labeling-z-SFsspa/lib/python3.9/site-packages/redis/client.py", line 1153, in _send_command_parse_response
    return self.parse_response(conn, command_name, **options)
  File "/home/vagrant/.local/share/virtualenvs/white-labeling-z-SFsspa/lib/python3.9/site-packages/redis/client.py", line 1192, in parse_response
    response = connection.read_response()
  File "/home/vagrant/.local/share/virtualenvs/white-labeling-z-SFsspa/lib/python3.9/site-packages/redis/connection.py", line 800, in read_response
    response = self._parser.read_response(disable_decoding=disable_decoding)
  File "/home/vagrant/.local/share/virtualenvs/white-labeling-z-SFsspa/lib/python3.9/site-packages/redis/connection.py", line 364, in read_response
    response = self.encoder.decode(response)
  File "/home/vagrant/.local/share/virtualenvs/white-labeling-z-SFsspa/lib/python3.9/site-packages/redis/connection.py", line 124, in decode
    value = value.decode(self.encoding, self.encoding_errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

I have latest version of django-redis. What's wrong with that?

**Comment by korsar182** [comment]
Sorry, wrong setting decode_responses=True

**Comment by AditMulyadi** [comment]
Hi @korsar182, how do you fix the error, just change the decode_responses to False?

**Comment by AditMulyadi** [comment]
Hi @korsar182, how do you fix the error, just change the decode_responses to False?

**Comment by AditMulyadi** [comment]
Hi @korsar182, how do you fix the error, just change the decode_responses to False?

**Comment by korsar182** [comment]
Hi @AditMulyadi 
yea, setting "decode_responses": False did the trick)
