### ISSUE TITLE
redis.exceptions.ReadOnlyError: You can't write against a read only replica.

### ISSUE THREAD

**Issue by OlehObodin** [jazzband/django-redis#616]
**Describe the bug**
Production of my app is failing

**Expected behavior**
 up and running app

**Stack trace**
```redis.exceptions.ReadOnlyError: You can't write against a read only replica.
inventree-server    | [04/Jul/2022 14:00:20] "GET /accounts/login/?next=/ HTTP/1.0" 500 59
inventree-server    | [04/Jul/2022 14:00:20] "GET /favicon.ico HTTP/1.0" 302 0
inventree-server    | You can't write against a read only replica.
inventree-server    | Traceback (most recent call last):
inventree-server    |   File "/home/ubuntu/InvenTree/dev/env/lib/python3.9/site-packages/django_redis/cache.py", line 31, in _decorator
inventree-server    |     return method(self, *args, **kwargs)
inventree-server    |   File "/home/ubuntu/InvenTree/dev/env/lib/python3.9/site-packages/django_redis/cache.py", line 80, in set
inventree-server    |     return self.client.set(*args, **kwargs)
inventree-server    |   File "/home/ubuntu/InvenTree/dev/env/lib/python3.9/site-packages/django_redis/client/default.py", line 185, in set
inventree-server    |     raise ConnectionInterrupted(connection=client) from e
inventree-server    | django_redis.exceptions.ConnectionInterrupted: Redis ReadOnlyError: You can't write against a read only replica.
inventree-server    | 
inventree-server    | During handling of the above exception, another exception occurred:
inventree-server    | 
inventree-server    | Traceback (most recent call last):
inventree-server    |   File "/usr/local/lib/python3.9/wsgiref/handlers.py", line 137, in run
inventree-server    |     self.result = application(self.environ, self.start_response)
inventree-server    |   File "/home/ubuntu/InvenTree/dev/env/lib/python3.9/site-packages/django/core/handlers/wsgi.py", line 133, in __call__
inventree-server    |     response = self.get_response(request)
inventree-server    |   File "/home/ubuntu/InvenTree/dev/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 130, in get_response
inventree-server    |     response = self._middleware_chain(request)
inventree-server    |   File "/home/ubuntu/InvenTree/dev/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 49, in inner
inventree-server    |     response = response_for_exception(request, exc)
inventree-server    |   File "/home/ubuntu/InvenTree/dev/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 114, in response_for_exception
inventree-server    |     response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
inventree-server    |   File "/home/ubuntu/InvenTree/dev/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 153, in handle_uncaught_exception
inventree-server    |     return callback(request)
inventree-server    |   File "/home/ubuntu/InvenTree/dev/env/lib/python3.9/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
inventree-server    |     response = view_func(request, *args, **kwargs)
inventree-server    |   File "/home/ubuntu/InvenTree/dev/env/lib/python3.9/site-packages/django/views/defaults.py", line 97, in server_error
inventree-server    |     return HttpResponseServerError(template.render())
inventree-server    |   File "/home/ubuntu/InvenTree/dev/env/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
inventree-server    |     return self.template.render(context)
inventree-server    |   File "/home/ubuntu/InvenTree/dev/env/lib/python3.9/site-packages/django/template/base.py", line 170, in render
inventree-server    |     return self._render(context)
inventree-server    |   File "/home/ubuntu/InvenTree/dev/env/lib/python3.9/site-packages/django/template/base.py", line 162, in _render
inventree-server    |     return self.nodelist.render(context)
inventree-server    |   File "/home/ubuntu/InvenTree/dev/env/lib/python3.9/site-packages/django/template/base.py", line 938, in render
inventree-server    |     bit = node.render_annotated(context)
inventree-server    |   File "/home/ubuntu/InvenTree/dev/env/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
inventree-server    |     return self.render(context)
inventree-server    |   File "/home/ubuntu/InvenTree/dev/env/lib/python3.9/site-packages/django/template/loader_tags.py", line 150, in render
inventree-server    |     return compiled_parent._render(context)
inventree-server    |   File "/home/ubuntu/InvenTree/dev/env/lib/python3.9/site-packages/django/template/base.py", line 162, in _render
inventree-server    |     return self.nodelist.render(context)
inventree-server    |   File "/home/ubuntu/InvenTree/dev/env/lib/python3.9/site-packages/django/template/base.py", line 938, in render
inventree-server    |     bit = node.render_annotated(context)
inventree-server    |   File "/home/ubuntu/InvenTree/dev/env/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
inventree-server    |     return self.render(context)
inventree-server    |   File "/home/ubuntu/InvenTree/dev/env/lib/python3.9/site-packages/django/template/library.py", line 192, in render
inventree-server    |     output = self.func(*resolved_args, **resolved_kwargs)
inventree-server    |   File "/home/ubuntu/InvenTree/InvenTree/part/templatetags/inventree_extras.py", line 300, in settings_value
inventree-server    |     return InvenTreeSetting.get_setting(key)
inventree-server    |   File "/home/ubuntu/InvenTree/InvenTree/common/models.py", line 367, in get_setting
inventree-server    |     setting = cls.get_setting_object(key, **kwargs)
inventree-server    |   File "/home/ubuntu/InvenTree/InvenTree/common/models.py", line 353, in get_setting_object
inventree-server    |     setting.save_to_cache()
inventree-server    |   File "/home/ubuntu/InvenTree/InvenTree/common/models.py", line 98, in save_to_cache
inventree-server    |     cache.set(
inventree-server    |   File "/home/ubuntu/InvenTree/dev/env/lib/python3.9/site-packages/django_redis/cache.py", line 38, in _decorator
inventree-server    |     raise e.__cause__
inventree-server    |   File "/home/ubuntu/InvenTree/dev/env/lib/python3.9/site-packages/django_redis/client/default.py", line 175, in set
inventree-server    |     return bool(client.set(nkey, nvalue, nx=nx, px=timeout, xx=xx))
inventree-server    |   File "/home/ubuntu/InvenTree/dev/env/lib/python3.9/site-packages/redis/commands/core.py", line 2220, in set
inventree-server    |     return self.execute_command("SET", *pieces, **options)
inventree-server    |   File "/home/ubuntu/InvenTree/dev/env/lib/python3.9/site-packages/redis/client.py", line 1238, in execute_command
inventree-server    |     return conn.retry.call_with_retry(
inventree-server    |   File "/home/ubuntu/InvenTree/dev/env/lib/python3.9/site-packages/redis/retry.py", line 46, in call_with_retry
inventree-server    |     return do()
inventree-server    |   File "/home/ubuntu/InvenTree/dev/env/lib/python3.9/site-packages/redis/client.py", line 1239, in <lambda>
inventree-server    |     lambda: self._send_command_parse_response(
inventree-server    |   File "/home/ubuntu/InvenTree/dev/env/lib/python3.9/site-packages/redis/client.py", line 1215, in _send_command_parse_response
inventree-server    |     return self.parse_response(conn, command_name, **options)
inventree-server    |   File "/home/ubuntu/InvenTree/dev/env/lib/python3.9/site-packages/redis/client.py", line 1254, in parse_response
inventree-server    |     response = connection.read_response()
inventree-server    |   File "/home/ubuntu/InvenTree/dev/env/lib/python3.9/site-packages/redis/connection.py", line 839, in read_response
inventree-server    |     raise response
inventree-server    | redis.exceptions.ReadOnlyError: You can't write against a read only replica.
inventree-server    | [04/Jul/2022 14:00:20] "GET /accounts/login/?next=/favicon.ico HTTP/1.0" 500 59
```

**Environment (please complete the following information):**
 - Python version: 3.9
 - Django Redis Version: [django-redis>=5.0.0       
 - Django Version: 3.2.13
 - Redis Version:  7
 - redis-py Version: [e.g. 3.5.0]

**Comment by dancergraham** [comment]
Hello, it seems this can happen if the redis port is open on the server and there is no password on redis.  The redis instance can be hacked.

**Comment by some1ataplace** [comment]
This error occurs when you are trying to write data to a read-only replica of your Redis instance. A read-only replica is a copy of the primary Redis instance that can only be used for read operations, not write operations.

To resolve this issue, you can try the following:

1. Make sure you are connecting to the primary Redis instance, not a read-only replica. Check your Django settings and ensure that the connection string for your Redis cache points to the correct instance.

2. If you're using a managed Redis service (e.g., AWS ElastiCache, Azure Cache for Redis, or Google Cloud Memorystore), ensure that your Django application is connecting to the primary endpoint, not a replica endpoint.

3. If you're using Redis Sentinel for high availability, make sure that your Django settings are configured correctly to connect to the master instance. The django-redis documentation has a section on how to configure Django to work with Redis Sentinel: https://django-redis-cache.readthedocs.io/en/latest/advanced_configuration.html#using-redis-sentinel

4. If you have control over your Redis configuration, you can check the redis.conf file to ensure that the slave-read-only option is set to no for the instance you're connecting to. However, this is not recommended if you intentionally have read-only replicas for scaling or high availability purposes.

5. If you're using a custom cache backend with django-redis, make sure it's properly handling read and write operations and not mistakenly directing write operations to read-only replicas.

***
To set a password for Redis and close the Redis port from hackers, you should follow these steps:

1. Configure Redis to require a password:

Open the Redis configuration file (redis.conf) in a text editor. This file is usually located in /etc/redis/ or /etc/redis/redis.conf depending on your system.

Find the line that starts with requirepass and uncomment it by removing the # at the beginning of the line. Then, set a strong password after the requirepass directive. For example:
`
requirepass mystrongpassword`


Save and close the configuration file.

2. Restart Redis to apply the changes:

`sudo systemctl restart redis`


or

`sudo service redis restart`


3. Configure your Django project to use the password:

Install django-redis using pip:

`pip install django-redis`


In your Django project's settings file (settings.py), configure the CACHES setting to use the Redis password you set earlier:

```
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://:mystrongpassword@localhost:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

```

Replace mystrongpassword with the password you set in the Redis configuration file.

4. Close the Redis port from external access:

By default, Redis listens on all available network interfaces. To restrict Redis to listen only on the local interface (127.0.0.1), you can update the bind directive

in the Redis configuration file (redis.conf):

Find the line that starts with bind and set it to:

`bind 127.0.0.1`

If there are other IP addresses listed, remove them to ensure Redis only listens on the local interface.

Save and close the configuration file.

5. Restart Redis to apply the changes:

`sudo systemctl restart redis`

or

`sudo service redis restart`

By following these steps, you will have set a strong password for Redis and restricted its access to the local interface, making it more secure against hackers. Remember to keep your Redis password secure and update it regularly to maintain the security of your Redis instance.

**Comment by dancergraham** [comment]
I'm closing this issue as there have been no updates recently @OlehObodin please add more details if you think this is still a problem
