### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'connection_pool'

### ISSUE THREAD

**Issue by sohamM97** [jazzband/django-redis#663]
**Describe the bug**
We are trying to use django redis cache with sentinel and SSL connection in our application.

**To Reproduce**

Keep the CACHES setting on settings.py as follows:
```
# there our other settings which we take from .env too, but mentioning this here for clarity
REDIS_SSL = env("REDIS_SSL", bool, default=False)
# in our case, since REDIS_SSL is true, REDIS_PROTOCOL would be 'rediss'
REDIS_PROTOCOL = "rediss" if REDIS_SSL else "redis"

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        # The hostname in LOCATION is the primary (service / master) name
        "LOCATION": f"{REDIS_PROTOCOL}://{REDIS_MASTER}/{REDIS_DB}",
        "OPTIONS": {
            # While the default client will work, this will check you
            # have configured things correctly, and also create a
            # primary and replica pool for the service specified by
            # LOCATION rather than requiring two URLs.
            "CLIENT_CLASS": "django_redis.client.SentinelClient",
            # Sentinels which are passed directly to redis Sentinel.
            "SENTINELS": SENTINELS,
            # kwargs for redis Sentinel (optional).
            "SENTINEL_KWARGS": {
                "password": SENTINEL_PASSWORD,
                "ssl_certfile": REDIS_SSL_CERTFILE,
                "ssl_keyfile": REDIS_SSL_KEYFILE,
                "ssl_ca_certs": REDIS_SSL_CA_CERTS,
                "ssl_cert_reqs": None,
                "ssl": REDIS_SSL,
            },
            "SOCKET_TIMEOUT": SENTINEL_CONNECTION_TIMEOUT,
            "SOCKET_CONNECT_TIMEOUT": SENTINEL_CONNECTION_TIMEOUT,
            # You can still override the connection pool (optional).
            "CONNECTION_POOL_CLASS": "redis.sentinel.SentinelConnectionPool",
            "PASSWORD": REDIS_PASSWORD,
            "CONNECTION_POOL_KWARGS": {
                "ssl": REDIS_SSL,
                **(
                    {
                        "ssl_certfile": REDIS_SSL_CERTFILE,
                        "ssl_keyfile": REDIS_SSL_KEYFILE,
                        "ssl_ca_certs": REDIS_SSL_CA_CERTS,
                        "ssl_cert_reqs": None,
                    }
                    if REDIS_SSL
                    else {}
                ),
            },
        },
        "KEY_PREFIX": "cache",
        "TIMEOUT": CACHE_TIMEOUT,
    },
}
```
Note that we take the settings such as REDIS_MASTER, REDIS_DB etc from our environment file (.env), which we read using the [django-environ](https://github.com/joke2k/django-environ) library.

**Expected behavior**
The library should be able to connect to the sentinel-based setup and the application should start up properly on running the server. 

**Stack trace**
```
__init__() got an unexpected keyword argument 'connection_pool'
Traceback (most recent call last):
  File "/home/soham/envs/aistudio/lib/python3.9/site-packages/redis/connection.py", line 1435, in get_connection
    connection = self._available_connections.pop()
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/soham/aistudio/aeli_utils/cache.py", line 47, in get_from_cache
    return cache.get(key, default)
  File "/home/soham/envs/aistudio/lib/python3.9/site-packages/django_redis/cache.py", line 91, in get
    value = self._get(key, default, version, client)
  File "/home/soham/envs/aistudio/lib/python3.9/site-packages/django_redis/cache.py", line 31, in _decorator
    return method(self, *args, **kwargs)
  File "/home/soham/envs/aistudio/lib/python3.9/site-packages/django_redis/cache.py", line 98, in _get
    return self.client.get(key, default=default, version=version, client=client)
  File "/home/soham/envs/aistudio/lib/python3.9/site-packages/django_redis/client/default.py", line 258, in get
    value = client.get(key)
  File "/home/soham/envs/aistudio/lib/python3.9/site-packages/redis/commands/core.py", line 1790, in get
    return self.execute_command("GET", name)
  File "/home/soham/envs/aistudio/lib/python3.9/site-packages/redis/client.py", line 1255, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/home/soham/envs/aistudio/lib/python3.9/site-packages/redis/connection.py", line 1437, in get_connection
    connection = self.make_connection()
  File "/home/soham/envs/aistudio/lib/python3.9/site-packages/redis/connection.py", line 1479, in make_connection
    def release(self, connection):
  File "/home/soham/envs/aistudio/lib/python3.9/site-packages/redis/connection.py", line 1085, in __init__
    super().__init__(**kwargs)
  File "/home/soham/envs/aistudio/lib/python3.9/site-packages/redis/connection.py", line 941, in __init__
    super().__init__(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'connection_pool'
```

**Environment (please complete the following information):**
 - Python version: 3.9
 - Django Redis Version: 5.0.0 
 - Django Version: 3.2.6
 - Redis Version: 7.0.10
 - redis-py Version: 4.5.4

**Additional context**
Instead of keeping the LOCATION as `f"{REDIS_PROTOCOL}://{REDIS_MASTER}/{REDIS_DB}"`, if we keep it as `f"redis://{REDIS_MASTER}/{REDIS_DB}"`, the application works as expected. We are confused as to why we need to keep the protocol as `redis` even though we clearly want to use `rediss`.

**Comment by halicloud** [comment]
>>> from django.core.cache import cache
>>> cache.set("key", "value1", nx=True)
True
>>> cache.set("key", "value2", nx=True)
False
>>> cache.get("key")
"value1"

Use like this will raise TypeError: __init__() got an unexpected keyword argument 'connection_pool'

>>> from django_redis import get_redis_connection
>>> con = get_redis_connection("default")
>>> con
<redis.client.StrictRedis object at 0x2dc4510>

**Comment by grahamneville** [comment]
I'm also hitting this issue.
Are there any updates as to why this might be occurring?

**Comment by rheemskerk** [comment]
Same problem here.  Thanks for the monkey-patch although it is a bit hard to use in combination with the helm package we use to deploy the django application (netbox).
